### ISSUE TITLE
Integrate Auth API with Frontend

### ISSUE THREAD

**Issue by ujjwalnp** [Hunter-420/DevFlexPort#20]
## Description
This issue is created to integrate the authentication API with the frontend. The authentication API provides a login endpoint at `/auth/login` to authenticate users. The request document for the login API is provided below:

### API Endpoint
`/auth/login`

### Method
`POST`

### Request Example
```json
{
  "username": "username",
  "email": "example@example.com",
  "password": "password"
}
```

### Additional Details
Refer to the API documentation available at /api-docs for further details on the authentication API.

### Tasks

- [ ] Update frontend code to make a POST request to the `/auth/login` endpoint.

- [ ] Implement the necessary logic to handle user authentication on the frontend.
- [ ] Handle API responses appropriately (e.g., success, error).
- [ ] Test the integration thoroughly to ensure seamless authentication.

### Additional Notes
- Ensure that the frontend is updated to handle authentication tokens or sessions after successful login.
- Verify that error handling is implemented for cases such as invalid credentials or server errors.
- Follow the API documentation for any specific requirements or considerations.
